[package]
name = "lang"
version = "0.1.0"
edition = "2024"

[dependencies]
wat = "1.219"
punycode = "0.4"
wasm-bindgen = "0.2"
multipeek = "0.1"
toml = "0.8"

[profile.release]
strip = true
opt-level = "z"
lto = true
codegen-units = 1

[lib]
crate-type = ["cdylib"]

[package.metadata.wasm-pack.profile.release]
wasm-opt = ["--enable-bulk-memory", "-O2"]
