[package]
name = "lang"
version = "0.1.0"
edition = "2024"

[dependencies]
wasm-encoder = "0.233"
punycode = "0.4"
wasm-bindgen = "0.2"
multipeek = "0.1"
toml = "0.8"
wasmparser = "0.235"
wasmprinter = "0.235"

[profile.release]
strip = true
opt-level = "z"
lto = true
codegen-units = 1

[lib]
crate-type = ["cdylib", "lib"]

[package.metadata.wasm-pack.profile.release]
wasm-opt = ["--enable-bulk-memory", "-O2"]
