[workspace]
members = [".", "cli", "lsp"]

[package]
name = "halcyon-lib"
version = "2026.3.3"
authors = ["Logan Gatlin <logan@gatlintc.com>"]
edition = "2024"
description = "Compiler backend for the Halcyon programming language"
readme = "./README.md"
homepage = "https://halcyon-lang.dev"
repository = "https://github.com/logan-gatlin/halcyon"
license = "MIT"
keywords = ["compiler", "functional programming", "wasm"]
categories = ["wasm", "compiler"]

[dependencies]
wasm-encoder = "0.244"
punycode = "0.4"
wasm-bindgen = "0.2"
multipeek = "0.1"
toml = {version = "0.9", default-features = false, features = ["parse", "serde"]}
indexmap = { version = "2.11", features = ["serde"] }
wasmparser = {version = "0.244"}
wasmprinter = "0.244"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
postcard = { version = "1", features = ["use-std"] }
colored = "3"
codespan-reporting = { version = "0.13", features = ["termcolor"] }
indoc = "2"
unicode_names2 = "2"
derive-new = "0.5"
paste = "1"
enum-iterator = "2.3"
rowan = "0.16"
itertools = "0.14"
inflections = "1.1"
tracing = "0.1"
include_dir = "0.7"
gimli = { version = "0.32", features = ["write"] }
rayon = "1.11"

[dev-dependencies]
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
js-sys = "0.3"

[profile.release]
strip = true
opt-level = "z"
lto = true
codegen-units = 1

[profile.dev.package.wasmtime]
opt-level = 1

[profile.dev.package.wasmtime-wasi]
opt-level = 1

[lib]
crate-type = ["cdylib", "lib"]

[lints.rust]
mismatched_lifetime_syntaxes = "deny"

[lints.clippy]
all = { level = "deny", priority = -1 }
exit = "deny"
empty_structs_with_brackets = "deny"
if_then_some_else_none = "deny"
infinite_loop = "deny"
map_with_unused_argument_over_ranges = "deny"
missing_assert_message = "deny"
missing_asserts_for_indexing = "deny"
mutex_atomic = "deny"
mutex_integer = "deny"
panic = "deny"
rc_buffer = "deny"
rc_mutex = "deny"
return_and_then = "deny"
self_named_module_files = "deny"
string_lit_chars_any = "deny"
string_lit_as_bytes = "deny"
string_slice = "deny"
try_err = "deny"
large_enum_variant = "allow"
result_large_err = "allow"
print_stdout = "warn"
print_stderr = "warn"
todo = "warn"
unwrap_used = "warn"

[package.metadata.wasm-pack.profile.release]
wasm-opt = ["--enable-bulk-memory", "-O2"]
