[package]
name = "halcyon-lsp"
version = "2026.3.4"
authors = ["Logan Gatlin <logan@gatlintc.com>"]
edition = "2024"
description = "Language Server Protocol implementation for Halcyon"
license = "MIT"

[dependencies]
halcyon-lib = { path = ".." }
lsp-server = "0.7"
lsp-types = "0.97"
serde_json = "1"
serde = { version = "1", features = ["derive"] }
url = "2"
inflections = "1.1"
crossbeam-channel = "0.5"

[lints.rust]
mismatched_lifetime_syntaxes = "deny"
